"""added image_directory table

Revision ID: 002_88971660dfff
Revises: 001_743f0de08461
Create Date: 2017-10-18 15:57:34.516000

"""
from alembic import op
import sqlalchemy as db


# revision identifiers, used by Alembic.
revision = '002_88971660dfff'
down_revision = '001_743f0de08461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_directory',
        db.Column('id', db.Integer(), nullable=False),
        db.Column('path', db.String(length=512), nullable=True),
        db.PrimaryKeyConstraint('id'),
        db.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_directory')
    # ### end Alembic commands ###
